language: php
os: linux
php: 
  - '5.6'
  - '7.2'
  - '7.3'
  - '7.4'
env:
  global:
    - PHPUNIT_VERSION="travis"
    - php: 5.6
      env: PHPCS_VERSION="2.8.*"
    - php: 7.0
      env: PHPCS_VERSION="2.6.*"
    - php: 7.1
      env: PHPCS_VERSION="3.1.*"
    - php: 7.2
      env: PHPCS_VERSION="3.3.*"
    - php: 7.3
      env: PHPCS_VERSION="3.4.*" LINT=1
    - php: 7.3
      env: PHPCS_VERSION="dev-master"
    - php: 7.4
      env: PHPCS_VERSION=">=2.6,<3.0" LINT=1
    - php: 7.4
      env: PHPCS_VERSION="2.6.0"
before_script:
  - composer require --dev phpcompatibility/php-compatibility
  - composer require --dev squizlabs/php_codesniffer:${PHPCS_VERSION}
  - composer require --dev php-coveralls/php-coveralls
  - composer install
script:
  - phpunit
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/phpcs --config-set installed_paths vendor/phpcompatibility/php-compatibility
  - vendor/bin/phpcs --ignore=*/vendor/*,*/js/* --standard=PHPCompatibility . 
after_success:
  - travis_retry php vendor/bin/php-coveralls
