language: php
os: linux
php:
  - '7.2'
  - '7.3'
  - '7.4'
before_script:
  - composer require --dev squizlabs/php_codesniffer
  - composer install
script:
  - phpunit
  - vendor/bin/phpcs -i
  - vendor/bin/phpcs --ignore=*/vendor/* --standard=PHPCompatibility . 
