language: php
os: linux
php: 
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
before_script:
  - composer update
  - composer install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter 
  - chmod +x ./cc-test-reporter 
  - ./cc-test-reporter before-build
script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml.dist
  #- vendor/bin/phpunit --coverage-clover ./clover.xml
  - vendor/bin/phpcs --version 
  - vendor/bin/phpcs --config-set installed_paths vendor/phpcompatibility/php-compatibility
  - vendor/bin/phpcs --ignore=*/vendor/*,*/js/*,*\.inc* --standard=PHPCompatibility . 
  - vendor/bin/codecept run unit --coverage --coverage-xml
after_script:
  - mv tests/_output/coverage.xml clover.xml 
  - ./cc-test-reporter after-build --coverage-input-type clover --id 66f284dd652099755bd327994fe7ac9cefdae7090b426969a28daee741650a3e --exit-code $TRAVIS_TEST_RESULT
  - vendor/bin/coveralls -v
after_success:
  - travis_retry php vendor/bin/php-coveralls
