language: php
os: linux
php: 
  - '5.6'
  - '7.2'
  - '7.3'
  - '7.4'
env:
  global:
    - PHPUNIT_VERSION="travis"
  matrix:
    - PHPCS_VERSION="2.6.0"
before_script:
  - composer require --dev phpcompatibility/php-compatibility
  - composer require --dev squizlabs/php_codesniffer
  - composer require --dev php-coveralls/php-coveralls
  - composer install
script:
  - phpunit
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/phpcs --config-set installed_paths vendor/phpcompatibility/php-compatibility
  - vendor/bin/phpcs --ignore=*/vendor/*,*/js/* --standard=PHPCompatibility . 
after_success:
  - travis_retry php vendor/bin/php-coveralls
