language: php
os: linux
php:
  - '5.6'
  - '7.2'
  - '7.3'
  - '7.4'
before_script:
  - composer self-update
  - composer require atoum/atoum
  - composer install
script:
  - phpunit
  - vendor/bin/atoum
