language: php
os: linux
php: 
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
before_install: echo "error_reporting = E_ALL & ~E_DEPRECATED" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
before_script:
  - composer update
  - composer install
script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/phpcs --version 
  - vendor/bin/phpcs --config-set installed_paths vendor/phpcompatibility/php-compatibility
  - vendor/bin/phpcs --ignore=*/vendor/*,*/js/*,*\.inc* --standard=PHPCompatibility . 
after_success:
  - travis_retry php vendor/bin/php-coveralls
