language: php
os: linux
php:
  - '5.6'
  - '7.2'
  - '7.3'
  - '7.4'
before_script:
  - composer require --dev squizlabs/php_codesniffer
  - composer install
script:
  - phpunit
  - vendor/bin/phpcs . 
